server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: seata-client-bank1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///bank1
    username: root
    password: yzh123


