
server:
  port: 8082


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: seata-client-bank2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///bank2
    username: root
    password: yzh123